<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        \DB::table('cities')->insert([
            ['name' => 'Kabul', 'country_id' => 2],
            ['name' => 'Kandahar', 'country_id' => 2],
            ['name' => 'Mariehamn', 'country_id' => 52],
            ['name' => 'Föglö', 'country_id' => 52],
            ['name' => 'Tirana', 'country_id' => 3],
            ['name' => 'Durrës', 'country_id' => 3],
            ['name' => 'Berlín', 'country_id' => 4],
            ['name' => 'Múnich', 'country_id' => 4],
            ['name' => 'Andorra la Vieja', 'country_id' => 5],
            ['name' => 'Escaldes-Engordany', 'country_id' => 5],
            ['name' => 'Luanda', 'country_id' => 6],
            ['name' => 'Huambo', 'country_id' => 6],
            ['name' => 'The Valley', 'country_id' => 7],
            ['name' => 'Blowing Point', 'country_id' => 7],
            ['name' => 'Villa Las Estrellas', 'country_id' => 8],
            ['name' => 'McMurdo', 'country_id' => 8],
            ['name' => 'Saint John’s', 'country_id' => 9],
            ['name' => 'All Saints', 'country_id' => 9],
            ['name' => 'Willemstad', 'country_id' => 10],
            ['name' => 'Oranjestad', 'country_id' => 10],
            ['name' => 'Riad', 'country_id' => 11],
            ['name' => 'Yeda', 'country_id' => 11],
            ['name' => 'Argel', 'country_id' => 12],
            ['name' => 'Orán', 'country_id' => 12],
            ['name' => 'Buenos Aires', 'country_id' => 13],
            ['name' => 'Córdoba', 'country_id' => 13],
            ['name' => 'Ereván', 'country_id' => 14],
            ['name' => 'Giumri', 'country_id' => 14],
            ['name' => 'Oranjestad', 'country_id' => 15],
            ['name' => 'Santa Cruz', 'country_id' => 15],
            ['name' => 'Sídney', 'country_id' => 16],
            ['name' => 'Melbourne', 'country_id' => 16],
            ['name' => 'Viena', 'country_id' => 17],
            ['name' => 'Graz', 'country_id' => 17],
            ['name' => 'Bakú', 'country_id' => 18],
            ['name' => 'Ganja', 'country_id' => 18],
            ['name' => 'Nasáu', 'country_id' => 19],
            ['name' => 'Freeport', 'country_id' => 19],
            ['name' => 'Manama', 'country_id' => 20],
            ['name' => 'Riffa', 'country_id' => 20],
            ['name' => 'Daca', 'country_id' => 21],
            ['name' => 'Chittagong', 'country_id' => 21],
            ['name' => 'Bridgetown', 'country_id' => 22],
            ['name' => 'Holetown', 'country_id' => 22],
            ['name' => 'Minsk', 'country_id' => 23],
            ['name' => 'Gómel', 'country_id' => 23],
            ['name' => 'Bruselas', 'country_id' => 24],
            ['name' => 'Amberes', 'country_id' => 24],
            ['name' => 'Ciudad de Belice', 'country_id' => 25],
            ['name' => 'San Ignacio', 'country_id' => 25],
            ['name' => 'Cotonú', 'country_id' => 26],
            ['name' => 'Porto Novo', 'country_id' => 26],
            ['name' => 'Hamilton', 'country_id' => 27],
            ['name' => 'Saint George', 'country_id' => 27],
            ['name' => 'Thimphu', 'country_id' => 28],
            ['name' => 'Phuntsholing', 'country_id' => 28],
            ['name' => 'La Paz', 'country_id' => 29],
            ['name' => 'Santa Cruz de la Sierra', 'country_id' => 29],
            ['name' => 'Sarajevo', 'country_id' => 30],
            ['name' => 'Bania Luka', 'country_id' => 30],
            ['name' => 'Gaborone', 'country_id' => 31],
            ['name' => 'Francistown', 'country_id' => 31],
            ['name' => 'Recife', 'country_id' => 33],
            ['name' => 'São Paulo', 'country_id' => 33],
            ['name' => 'Bandar Seri Begawan', 'country_id' => 34],
            ['name' => 'Kuala Belait', 'country_id' => 34],
            ['name' => 'Sofía', 'country_id' => 35],
            ['name' => 'Plovdiv', 'country_id' => 35],
            ['name' => 'Uagadugú', 'country_id' => 36],
            ['name' => 'Bobo-Dioulasso', 'country_id' => 36],
            ['name' => 'Buyumbura', 'country_id' => 37],
            ['name' => 'Gitega', 'country_id' => 37],
            ['name' => 'Praia', 'country_id' => 38],
            ['name' => 'Mindelo', 'country_id' => 38],
            ['name' => 'George Town', 'country_id' => 39],
            ['name' => 'West Bay', 'country_id' => 39],
            ['name' => 'Nom Pen', 'country_id' => 40],
            ['name' => 'Batdambang', 'country_id' => 40],
            ['name' => 'Yaundé', 'country_id' => 41],
            ['name' => 'Duala', 'country_id' => 41],
            ['name' => 'Ottawa', 'country_id' => 42],
            ['name' => 'Toronto', 'country_id' => 42],
            ['name' => 'Bogotá', 'country_id' => 1],
            ['name' => 'Medellín', 'country_id' => 1],
            ['name' => 'Cali', 'country_id' => 1],
            ['name' => 'Barranquilla', 'country_id' => 1],
            ['name' => 'Cartagena', 'country_id' => 1],
            ['name' => 'Cúcuta', 'country_id' => 1],
            ['name' => 'Bucaramanga', 'country_id' => 1],
            ['name' => 'Pereira', 'country_id' => 1],
            ['name' => 'Manizales', 'country_id' => 1],
            ['name' => 'Santa Marta', 'country_id' => 1],
            ['name' => 'Ibagué', 'country_id' => 1],
            ['name' => 'Villavicencio', 'country_id' => 1],
            ['name' => 'Neiva', 'country_id' => 1],
            ['name' => 'Armenia', 'country_id' => 1],
            ['name' => 'Popayán', 'country_id' => 1],
            ['name' => 'Pasto', 'country_id' => 1],
            ['name' => 'Montería', 'country_id' => 1],
            ['name' => 'Valledupar', 'country_id' => 1],
            ['name' => 'Sincelejo', 'country_id' => 1],
            ['name' => 'Riohacha', 'country_id' => 1],
            ['name' => 'Tunja', 'country_id' => 1],
            ['name' => 'Florencia', 'country_id' => 1],
            ['name' => 'Quibdó', 'country_id' => 1],
            ['name' => 'Mocoa', 'country_id' => 1],
            ['name' => 'San Andrés', 'country_id' => 1],
            ['name' => 'Leticia', 'country_id' => 1],
        ]);
    }
}
